# Updated config.yaml

- name: Fetch homepage
  url: https://example.com/
  method: GET
  headers:
    user-agent: fetch-monitor

- name: Fetch careers
  url: https://example.com/careers
  method: GET

- name: Fetch API health
  url: https://jsonplaceholder.typicode.com/posts/1
  method: GET
  headers:
    user-agent: fetch-monitor

- name: Fetch rewards page
  url: https://jsonplaceholder.typicode.com/users/1
  method: GET
  headers:
    user-agent: fetch-monitor

- name: Example JSON Placeholder GET
  url: https://jsonplaceholder.typicode.com/posts/2
  method: GET

- name: Example JSON Placeholder POST
  url: https://jsonplaceholder.typicode.com/posts
  method: POST
  headers:
    content-type: application/json
    user-agent: fetch-monitor
  body: '{"title": "foo", "body": "bar", "userId": 1}'

- name: Example with only URL
  url: https://example.com
